services:
  postgres: 
    image: postgres:18-alpine 
    restart: always 
    environment: 
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: recipes 
    ports: 
      - "5432:5432"
    networks: 
      - db-network
    volumes: 
      - postgres_data:/var/lib/postgresql/data

networks: 
  db-network: 
volumes: 
  postgres_data: